"""Added time_created & valid_until columns

Revision ID: 0ab5d9a9e75a
Revises: 313aa36e86a8
Create Date: 2024-04-10 13:40:12.156605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ab5d9a9e75a'
down_revision = '313aa36e86a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortened_urls', sa.Column('time_created', sa.DateTime(timezone=True), nullable=True))
    op.add_column('shortened_urls', sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shortened_urls', 'valid_until')
    op.drop_column('shortened_urls', 'time_created')
    # ### end Alembic commands ###
