"""chanhe short_url column size

Revision ID: 4cb303f9e244
Revises: 0ab5d9a9e75a
Create Date: 2025-04-02 12:43:21.738490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb303f9e244'
down_revision = '0ab5d9a9e75a'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('short_link', 'short_link',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=64),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('short_link', 'short_link',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    ### end Alembic commands ###
 